filebeat.inputs:
  - type: filestream
    id: "nfp-logs"
    enabled: true
    paths:
      - /var/log/nfp-hwdbg-srv.log
      - /var/log/nfp-sdk6-rte.log
      - /var/log/nfp-sdk6-rtelib.log
    fields:
      service: nfp
      event.dataset: nfp.logs
    fields_under_root: true

  - type: filestream
    id: "int-metrics"
    enabled: true
    paths:
      - /var/spool/int/*.ndjson
    exclude_files: ['\.open$']
    parsers:
      - ndjson:
          add_error_key: true
          target: ""
    prospector.scanner.fingerprint.length: 64
    prospector.scanner.fingerprint.offset: 0
    fields:
      service: int
      event.dataset: int.metrics
    fields_under_root: true

output.logstash:
  hosts: ["localhost:5044"]
  ssl.enabled: false
