filebeat.inputs:
  - type: filestream
    id: "nfp-logs"
    enabled: true
    paths:
      - /var/log/nfp-hwdbg-srv.log
      - /var/log/nfp-sdk6-rte.log
      - /var/log/nfp-sdk6-rtelib.log

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "diciembre"
  ssl.certificate_authorities: ["/etc/elasticsearch/certs/http_ca.crt"]
